--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/6/2023 7:29:18 AM
-- Server version: 8.0.31
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS data_police;

CREATE DATABASE data_police
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE data_police;

--
-- Create table `t_category`
--
CREATE TABLE t_category (
  cat_id int NOT NULL AUTO_INCREMENT,
  cat_name varchar(100) DEFAULT NULL,
  cat_name_en varchar(100) DEFAULT NULL,
  PRIMARY KEY (cat_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `name` on table `t_category`
--
ALTER TABLE t_category
ADD UNIQUE INDEX name (cat_name);

--
-- Create index `cat_name_n_UNIQUE` on table `t_category`
--
ALTER TABLE t_category
ADD UNIQUE INDEX cat_name_n_UNIQUE (cat_name_en);

DELIMITER $$

--
-- Create procedure `sp_update_cat`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_update_cat (pi_id int,
pi_name varchar(100),
pi_cat_name_en varchar(100))
sp:
  BEGIN
    DECLARE v_count int;
    DECLARE v_id nvarchar(100);

    IF IFNULL(pi_name, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'name cannot be empty';
    END IF;

    #
    SELECT
      cat_id INTO v_id
    FROM t_category
    WHERE cat_id = pi_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'категори олдсонгүй!';
    END IF;
    UPDATE t_category
    SET cat_name = pi_name,
        cat_name_en = pi_cat_name_en
    WHERE cat_id = pi_id;
  END
  $$

--
-- Create procedure `sp_delete_cat`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_delete_cat (pi_id int)
sp:
  BEGIN
    DECLARE v_id int;

    IF IFNULL(pi_id, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'id cannot be empty';
    END IF;

    #
    SELECT
      cat_id INTO v_id
    FROM t_category
    WHERE cat_id = pi_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'категори олдсонгүй!';
    END IF;
    DELETE
      FROM t_category
    WHERE cat_id = pi_id;
  END
  $$

--
-- Create procedure `sp_create_cat`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_cat (pi_name varchar(100),
pi_name_en varchar(100))
sp:
  BEGIN
    DECLARE v_count int;
    IF IFNULL(pi_name, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'name cannot be empty';
    END IF;

    #
    SELECT
      COUNT(*) INTO v_count
    FROM t_category
    WHERE cat_name = pi_name
    ;


    IF v_count >= 1 THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Category exists!';
    END IF;
    INSERT INTO t_category (cat_name, cat_name_en)
      VALUES (pi_name, pi_name_en);
  END
  $$

DELIMITER ;

--
-- Create table `t_sub_category`
--
CREATE TABLE t_sub_category (
  sub_cat_id int NOT NULL AUTO_INCREMENT,
  cat_id int DEFAULT NULL,
  sub_cat_name varchar(100) DEFAULT NULL,
  sub_cat_name_en varchar(100) DEFAULT NULL,
  sub_cat_link mediumtext DEFAULT NULL,
  PRIMARY KEY (sub_cat_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 16,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE t_sub_category
ADD CONSTRAINT t_sub_category_ibfk_1 FOREIGN KEY (cat_id)
REFERENCES t_category (cat_id) ON DELETE CASCADE ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_update_sub_cat`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_update_sub_cat (pi_cat_id int,
pi_sub_cat_id int,
pi_name varchar(100),
pi_name_en varchar(100))
sp:
  BEGIN
    DECLARE v_count int;
    DECLARE v_id nvarchar(100);

    #

    SELECT
      cat_id INTO v_id
    FROM t_category
    WHERE cat_id = pi_cat_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Эцэг категори олдсонгүй!';
    END IF;

    SELECT
      sub_cat_id,
      COUNT(*) AS count INTO v_id, v_count
    FROM t_sub_category
    WHERE sub_cat_name = pi_name
    GROUP BY sub_cat_id
    ;

    UPDATE t_sub_category
    SET cat_id = pi_cat_id,
        sub_cat_name = pi_name,
        sub_cat_name_en = pi_name_en
    WHERE sub_cat_id = pi_sub_cat_id;
  END
  $$

--
-- Create procedure `sp_delete_sub_cat`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_delete_sub_cat (pi_id int)
sp:
  BEGIN
    DECLARE v_id int;

    IF IFNULL(pi_id, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'id cannot be empty';
    END IF;

    #
    SELECT
      sub_cat_id INTO v_id
    FROM t_sub_category
    WHERE sub_cat_id = pi_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'категори олдсонгүй!';
    END IF;
    DELETE
      FROM t_sub_category
    WHERE sub_cat_id = pi_id;
  END
  $$

--
-- Create procedure `sp_create_sub_cat`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_sub_cat (pi_cat_id int,
pi_name varchar(100),
pi_name_en varchar(100),
pi_link mediumtext)
sp:
  BEGIN
    DECLARE v_count int;
    DECLARE v_id nvarchar(100);
    IF IFNULL(pi_name, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'name cannot be empty';
    END IF;

    #

    SELECT
      cat_id INTO v_id
    FROM t_category
    WHERE cat_id = pi_cat_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Эцэг категори олдсонгүй!';
    END IF;

    SELECT
      COUNT(*) INTO v_count
    FROM t_sub_category
    WHERE sub_cat_name = pi_name
    ;


    IF v_count >= 1 THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Бүртгэлтэй байна!';
    END IF;

    INSERT INTO t_sub_category (cat_id, sub_cat_name, sub_cat_name_en, sub_cat_link)
      VALUES (pi_cat_id, pi_name, pi_name_en, pi_link);
  END
  $$

DELIMITER ;

--
-- Create table `t_news`
--
CREATE TABLE t_news (
  n_id int NOT NULL AUTO_INCREMENT,
  n_img mediumtext DEFAULT NULL,
  n_title text DEFAULT NULL,
  n_desc mediumtext DEFAULT NULL,
  n_content longtext DEFAULT NULL,
  n_viewcount int DEFAULT 0,
  sub_cat_id int DEFAULT NULL,
  createdAt timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  n_files mediumtext DEFAULT NULL,
  PRIMARY KEY (n_id),
  UNIQUE INDEX n_id (n_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1051,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `sub_cat_id_idx` on table `t_news`
--
ALTER TABLE t_news
ADD INDEX sub_cat_id_idx (sub_cat_id);

--
-- Create foreign key
--
ALTER TABLE t_news
ADD CONSTRAINT sub_cat_id FOREIGN KEY (sub_cat_id)
REFERENCES t_sub_category (sub_cat_id) ON DELETE SET NULL ON UPDATE SET NULL;

DELIMITER $$

--
-- Create procedure `sp_update_news`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_update_news (pi_id int,
pi_img longtext,
pi_title mediumtext,
pi_desc mediumtext,
pi_content longtext,
pi_child_sub_cat_id int,
pi_n_files mediumtext)
BEGIN

  DECLARE v_id int;

  IF IFNULL(pi_id, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'id cannot be empty';
  END IF;


  IF IFNULL(pi_title, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'title cannot be empty';
  END IF;

  IF IFNULL(pi_desc, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'desc cannot be empty';
  END IF;

  IF IFNULL(pi_child_sub_cat_id, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'category cannot be empty';
  END IF;

  SELECT
    n_id INTO v_id
  FROM t_news
  WHERE n_id = pi_id
  ;

  IF v_id IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Мэдээ олдсонгүй!';
  END IF;

  UPDATE t_news
  SET n_img = pi_img,
      n_title = pi_title,
      n_desc = pi_desc,
      n_content = pi_content,
      sub_cat_id = pi_child_sub_cat_id,
      n_files = pi_n_files
  WHERE n_id = pi_id;

END
$$

--
-- Create procedure `sp_insert_news_img`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_insert_news_img (pi_id int,
pi_img longtext,
pi_files mediumtext)
BEGIN

  DECLARE v_id int;

  IF IFNULL(pi_id, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'id cannot be empty';
  END IF;


  IF IFNULL(pi_img, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'img cannot be empty';
  END IF;

  SELECT
    n_id INTO v_id
  FROM t_news
  WHERE n_id = pi_id
  ;

  IF v_id IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Мэдээ олдсонгүй!';
  END IF;

  UPDATE t_news
  SET n_img = pi_img,
      n_files = pi_files
  WHERE n_id = pi_id;

END
$$

--
-- Create procedure `sp_filter_news_sub_cat_id`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_filter_news_sub_cat_id (pi_sub_cat_id int,
pi_skip int,
pi_limit int,
pi_sort int)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE start int;
  SET start = pi_skip - 1;

  IF IFNULL(pi_sub_cat_id, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'sub_cat_id cannot be empty';
  END IF;
  SELECT
    n_id,
    n_img,
    n_title,
    n_desc,
    n_content,
    n_viewcount,
    createdAt,
    t_sub_category.sub_cat_id,
    sub_cat_name
  FROM t_news
    INNER JOIN t_sub_category
      ON t_news.sub_cat_id = t_sub_category.sub_cat_id
  WHERE t_sub_category.sub_cat_id = pi_sub_cat_id LIMIT start, pi_limit;
END
$$

--
-- Create procedure `sp_filter_news_cat_id`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_filter_news_cat_id (pi_cat_id int,
pi_skip int,
pi_limit int,
pi_sort int)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE start int;
  SET start = pi_skip - 1;

  IF IFNULL(pi_cat_id, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'child_sub_cat_id cannot be empty';
  END IF;
  SELECT
    n_id,
    n_img,
    n_title,
    n_desc,
    n_content,
    n_viewcount,
    createdAt,
    t_category.cat_id,
    cat_name
  FROM t_news
    INNER JOIN t_sub_category
      ON t_news.sub_cat_id = t_sub_category.sub_cat_id
    INNER JOIN t_category
      ON t_sub_category.cat_id = t_category.cat_id
  WHERE t_category.cat_id = pi_cat_id LIMIT start, pi_limit;
END
$$

--
-- Create procedure `sp_delete_news`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_delete_news (pi_id int)
sp:
  BEGIN
    DECLARE v_id int;
    DECLARE v_img text;
    DECLARE v_files text;
    IF IFNULL(pi_id, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'id cannot be empty';
    END IF;

    #
    SELECT
      n_id INTO v_id
    FROM t_news
    WHERE n_id = pi_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'мэдээ олдсонгүй!';
    END IF;
    SELECT
      n_img,
      n_files INTO v_img, v_files
    FROM t_news
    WHERE n_id = pi_id;
    DELETE
      FROM t_news
    WHERE n_id = pi_id;
    SELECT
      v_img AS n_img,
      v_files AS n_files;
  END
  $$

--
-- Create procedure `sp_create_news`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_news (pi_img longtext,
pi_title mediumtext,
pi_desc mediumtext,
pi_content longtext,
pi_files mediumtext,
pi_child_sub_cat_id int)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE returnValue text;

  IF IFNULL(pi_title, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'title cannot be empty';
  END IF;

  IF IFNULL(pi_desc, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'desc cannot be empty';
  END IF;

  IF IFNULL(pi_child_sub_cat_id, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'category cannot be empty';
  END IF;

  INSERT INTO t_news (n_img, n_title, n_desc, n_content, n_files, sub_cat_id)
    VALUES (pi_img, pi_title, pi_desc, pi_content, pi_files, pi_child_sub_cat_id);
  SELECT
    MAX(n_id) AS n_id
  FROM t_news;

END
$$

DELIMITER ;

--
-- Create table `t_child_sub_category`
--
CREATE TABLE t_child_sub_category (
  child_sub_cat_id int NOT NULL AUTO_INCREMENT,
  sub_cat_id int DEFAULT NULL,
  child_sub_cat_name varchar(100) DEFAULT NULL,
  PRIMARY KEY (child_sub_cat_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `name` on table `t_child_sub_category`
--
ALTER TABLE t_child_sub_category
ADD UNIQUE INDEX name (child_sub_cat_name);

--
-- Create foreign key
--
ALTER TABLE t_child_sub_category
ADD CONSTRAINT t_child_sub_category_ibfk_1 FOREIGN KEY (sub_cat_id)
REFERENCES t_sub_category (sub_cat_id) ON DELETE CASCADE ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_update_child_sub_cat`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_update_child_sub_cat (pi_child_cat_id int,
pi_sub_cat_id int,
pi_name varchar(100))
sp:
  BEGIN
    DECLARE v_count int;
    DECLARE v_id int;
    DECLARE v_id1 int;

    #

    SELECT
      sub_cat_id INTO v_id
    FROM t_sub_category
    WHERE sub_cat_id = pi_sub_cat_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Эцэг категори олдсонгүй!';
    END IF;

    SELECT
      child_sub_cat_id INTO v_id1
    FROM t_child_sub_category
    WHERE child_sub_cat_id = pi_child_cat_id
    ;
    IF v_id1 IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'категори олдсонгүй!';
    END IF;

    SELECT
      child_sub_cat_id,
      COUNT(*) AS count INTO v_id, v_count
    FROM t_child_sub_category
    WHERE child_sub_cat_name = pi_name
    GROUP BY child_sub_cat_id
    ;

    UPDATE t_child_sub_category
    SET sub_cat_id = pi_sub_cat_id,
        child_sub_cat_name = pi_name
    WHERE child_sub_cat_id = pi_child_cat_id;
  END
  $$

--
-- Create procedure `sp_filter_news_child_sub_cat_id`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_filter_news_child_sub_cat_id (pi_child_sub_cat_id int,
pi_skip int,
pi_limit int,
pi_sort int)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;

  DECLARE start int;
  SET start = pi_skip - 1;

  IF IFNULL(pi_child_sub_cat_id, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'child_sub_cat_id cannot be empty';
  END IF;
  SELECT
    n_id,
    n_img,
    n_title,
    n_desc,
    n_content,
    n_viewcount,
    createdAt,
    t_news.child_sub_cat_id,
    child_sub_cat_name
  FROM t_news
    INNER JOIN t_child_sub_category
      ON t_news.child_sub_cat_id = t_child_sub_category.child_sub_cat_id
  WHERE t_child_sub_category.child_sub_cat_id = pi_child_sub_cat_id LIMIT start, pi_limit;
END
$$

--
-- Create procedure `sp_delete_child_sub_cat`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_delete_child_sub_cat (pi_id int)
sp:
  BEGIN
    DECLARE v_id int;

    IF IFNULL(pi_id, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'id cannot be empty';
    END IF;

    #
    SELECT
      child_sub_cat_id INTO v_id
    FROM t_child_sub_category
    WHERE child_sub_cat_id = pi_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'категори олдсонгүй!';
    END IF;
    DELETE
      FROM t_child_sub_category
    WHERE child_sub_cat_id = pi_id;
  END
  $$

--
-- Create procedure `sp_create_child_sub_cat`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_child_sub_cat (pi_sub_cat_id int,
pi_name varchar(100))
sp:
  BEGIN
    DECLARE v_count int;
    DECLARE v_id nvarchar(100);
    IF IFNULL(pi_sub_cat_id, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'id cannot be empty';
    END IF;

    #

    SELECT
      sub_cat_id INTO v_id
    FROM t_sub_category
    WHERE sub_cat_id = pi_sub_cat_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Эцэг категори олдсонгүй!';
    END IF;

    INSERT INTO t_child_sub_category (sub_cat_id, child_sub_cat_name)
      VALUES (pi_sub_cat_id, pi_name);
  END
  $$

--
-- Create procedure `sp_child_delete_sub_cat`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_child_delete_sub_cat (pi_id int)
sp:
  BEGIN
    DECLARE v_id int;

    IF IFNULL(pi_id, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'id cannot be empty';
    END IF;

    #
    SELECT
      child_sub_cat_id INTO v_id
    FROM t_child_sub_category
    WHERE child_sub_cat_id = pi_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'категори олдсонгүй!';
    END IF;
    DELETE
      FROM t_child_sub_category
    WHERE child_sub_cat_id = pi_id;
  END
  $$

DELIMITER ;

--
-- Create table `t_report_type`
--
CREATE TABLE t_report_type (
  type_id int NOT NULL AUTO_INCREMENT,
  type_name varchar(100) DEFAULT NULL,
  type_img varchar(100) DEFAULT NULL,
  PRIMARY KEY (type_id),
  UNIQUE INDEX type_id (type_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 182,
AVG_ROW_LENGTH = 744,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `sp_create_r_type`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_r_type (pi_img mediumtext,
pi_name mediumtext)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE returnValue text;

  IF IFNULL(pi_name, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'name cannot be empty';
  END IF;

  INSERT INTO t_report_type (type_img, type_name)
    VALUES (pi_img, pi_name);
  SELECT
    MAX(type_id) AS type_id
  FROM t_report_type;

END
$$

DELIMITER ;

--
-- Create table `t_user_reports`
--
CREATE TABLE t_user_reports (
  r_id int NOT NULL AUTO_INCREMENT,
  u_phone int DEFAULT NULL,
  u_name varchar(100) DEFAULT NULL,
  type_id int DEFAULT NULL,
  r_desc text DEFAULT NULL,
  r_date date DEFAULT NULL,
  c_longitude varchar(200) DEFAULT NULL,
  c_latitude varchar(200) DEFAULT NULL,
  is_imported varchar(10) DEFAULT 'false',
  createdAt timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  t_status int DEFAULT 0,
  PRIMARY KEY (r_id),
  UNIQUE INDEX r_id (r_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE t_user_reports
ADD CONSTRAINT t_user_reports_ibfk_1 FOREIGN KEY (type_id)
REFERENCES t_report_type (type_id) ON DELETE CASCADE ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_show_reports`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_show_reports (pi_skip int,
pi_limit int,
pi_sort int)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE start int;
  SET start = pi_skip - 1;
  SELECT
    *
  FROM data_police.t_user_reports
    LEFT JOIN t_report_type
      ON t_user_reports.type_id = t_report_type.type_id
  WHERE t_status = 0 LIMIT start, pi_limit;
END
$$

--
-- Create procedure `sp_filter_reports_typeName`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_filter_reports_typeName (pi_type varchar(100),
pi_skip int,
pi_limit int,
pi_sort int)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE start int;
  SET start = pi_skip - 1;
  SELECT
    *
  FROM data_police.t_user_reports
    LEFT JOIN t_report_type
      ON t_user_reports.type_id = t_report_type.type_id
  WHERE t_status = 0
  AND t_report_type.type_name = pi_type LIMIT start, pi_limit;
END
$$

--
-- Create procedure `sp_filter_reports_typeId`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_filter_reports_typeId (pi_type varchar(100),
pi_skip int,
pi_limit int,
pi_sort int)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE start int;
  SET start = pi_skip - 1;
  SELECT
    *
  FROM data_police.t_user_reports
    LEFT JOIN t_report_type
      ON t_user_reports.type_id = t_report_type.type_id
  WHERE t_status = 0
  AND t_report_type.type_id = pi_type
  ORDER BY createdAt DESC LIMIT start, pi_limit;
END
$$

DELIMITER ;

--
-- Create table `t_crime_sub_type`
--
CREATE TABLE t_crime_sub_type (
  c_sub_type_id int NOT NULL AUTO_INCREMENT,
  c_sub_type_name varchar(500) DEFAULT NULL,
  type_id int DEFAULT NULL,
  PRIMARY KEY (c_sub_type_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2056,
AVG_ROW_LENGTH = 199,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `c_sub_type_name_UNIQUE` on table `t_crime_sub_type`
--
ALTER TABLE t_crime_sub_type
ADD UNIQUE INDEX c_sub_type_name_UNIQUE (c_sub_type_name);

--
-- Create foreign key
--
ALTER TABLE t_crime_sub_type
ADD CONSTRAINT t_crime_sub_type_ibfk_1 FOREIGN KEY (type_id)
REFERENCES t_report_type (type_id) ON DELETE SET NULL ON UPDATE SET NULL;

DELIMITER $$

--
-- Create procedure `sp_filter_imported_crimes`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_filter_imported_crimes (pi_cat_name varchar(200))
BEGIN

  DECLARE v_count int UNSIGNED DEFAULT 0;
  DECLARE v_id int;
  DECLARE v_check int;

  IF IFNULL(pi_cat_name, '') = '' THEN
    SET pi_cat_name = 'Хоосон';
  END IF;
  SELECT
    COUNT(*) INTO v_count
  FROM t_crime_sub_type
  WHERE c_sub_type_name LIKE CONCAT('%', pi_cat_name, '%');
  SELECT
    type_id INTO v_check
  FROM t_report_type
  WHERE type_name = 'Тодорхойгүй';
  IF IFNULL(v_check, '') = '' THEN
    INSERT INTO t_report_type (type_name)
      VALUES ('Тодорхойгүй');
  END IF;

  SELECT
    type_id INTO v_id
  FROM t_report_type
  WHERE type_name = 'Тодорхойгүй';
  IF v_count < 1 THEN
    INSERT INTO t_crime_sub_type (c_sub_type_name, type_id)
      VALUES (pi_cat_name, v_id);
  END IF;
END
$$

DELIMITER ;

--
-- Create table `t_department`
--
CREATE TABLE t_department (
  dep_id int NOT NULL AUTO_INCREMENT,
  dep_name varchar(200) DEFAULT NULL,
  PRIMARY KEY (dep_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 75,
AVG_ROW_LENGTH = 234,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `dep_name` on table `t_department`
--
ALTER TABLE t_department
ADD UNIQUE INDEX dep_name (dep_name);

--
-- Create table `t_crime`
--
CREATE TABLE t_crime (
  c_id int NOT NULL AUTO_INCREMENT,
  dep_name varchar(200) DEFAULT NULL,
  c_type varchar(100) DEFAULT NULL,
  c_sub_type_name varchar(500) DEFAULT NULL,
  c_date date DEFAULT NULL,
  c_longitude varchar(200) DEFAULT NULL,
  c_latitude varchar(200) DEFAULT NULL,
  c_is_family_violence varchar(10) DEFAULT NULL,
  last_updated_id int DEFAULT NULL,
  is_imported varchar(100) DEFAULT 'true',
  createdAt timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (c_id),
  UNIQUE INDEX c_id (c_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1004532,
AVG_ROW_LENGTH = 268,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE t_crime
ADD CONSTRAINT t_crime_ibfk_1 FOREIGN KEY (dep_name)
REFERENCES t_department (dep_name) ON DELETE SET NULL ON UPDATE SET NULL;

DELIMITER $$

--
-- Create procedure `sp_submit_report`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_submit_report (pi_r_id text,
pi_dep_name varchar(200),
pi_c_type varchar(100),
pi_c_sub_type_name mediumtext,
pi_c_date mediumtext,
pi_c_longitude longtext,
pi_c_latitude longtext,
pi_c_is_family_violence varchar(10),
pi_is_imported varchar(10))
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE returnValue text;

  IF IFNULL(pi_dep_name, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'dep_name cannot be empty';
  END IF;

  IF IFNULL(pi_c_type, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'c_type cannot be empty';
  END IF;

  IF IFNULL(pi_c_sub_type_name, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'c_sub_type_name cannot be empty';
  END IF;

  IF IFNULL(pi_c_date, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'date cannot be empty';
  END IF;

  IF IFNULL(pi_c_longitude, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'c_longitude cannot be empty';
  END IF;

  IF IFNULL(pi_c_latitude, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'c_latitude cannot be empty';
  END IF;

  IF IFNULL(pi_c_is_family_violence, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'c_is_family_violence cannot be empty';
  END IF;

  IF IFNULL(pi_is_imported, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'is_imported cannot be empty';
  END IF;

  INSERT INTO t_crime (dep_name, c_type, c_sub_type_name,
  c_date, c_longitude,
  c_latitude, c_is_family_violence, is_imported)
    VALUES (pi_dep_name, pi_c_type, pi_c_sub_type_name, pi_c_date, pi_c_longitude, pi_c_latitude, pi_c_is_family_violence, pi_is_imported);
  UPDATE t_user_reports
  SET t_status = 2
  WHERE r_id = pi_r_id;
  SELECT
    MAX(c_id) AS c_id
  FROM t_crime;
END
$$

DELIMITER ;

--
-- Create table `t_feedback`
--
CREATE TABLE t_feedback (
  f_id int NOT NULL AUTO_INCREMENT,
  f_name varchar(45) DEFAULT NULL,
  f_count int DEFAULT 0,
  PRIMARY KEY (f_id),
  UNIQUE INDEX f_id_UNIQUE (f_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `sp_create_feedback_options`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_feedback_options (pi_name varchar(100))
sp:
  BEGIN
    DECLARE v_count int;
    IF IFNULL(pi_name, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'name cannot be empty';
    END IF;

    #
    SELECT
      COUNT(*) INTO v_count
    FROM t_feedback
    WHERE f_name = pi_name
    ;


    IF v_count >= 1 THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'feedaback exists!';
    END IF;
    INSERT INTO t_feedback (f_name)
      VALUES (pi_name);
  END
  $$

DELIMITER ;

--
-- Create table `t_users`
--
CREATE TABLE t_users (
  u_id int NOT NULL AUTO_INCREMENT,
  u_phone int NOT NULL,
  u_password varchar(30) NOT NULL,
  u_phoneOtp char(1) DEFAULT NULL,
  u_firstName varchar(100) DEFAULT NULL,
  u_lastName varchar(100) DEFAULT NULL,
  u_birthday varchar(20) DEFAULT NULL,
  u_isAccountVerified varchar(10) DEFAULT NULL,
  f_id int DEFAULT NULL,
  createdAt timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (u_id),
  UNIQUE INDEX u_id (u_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `u_phone` on table `t_users`
--
ALTER TABLE t_users
ADD UNIQUE INDEX u_phone (u_phone);

--
-- Create foreign key
--
ALTER TABLE t_users
ADD CONSTRAINT t_users_ibfk_1 FOREIGN KEY (f_id)
REFERENCES t_feedback (f_id);

DELIMITER $$

--
-- Create procedure `sp_verifyOtp`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_verifyOtp (pi_phone nvarchar(100),
pi_otp nvarchar(100))
BEGIN
  DECLARE v_otp nvarchar(100);
  DECLARE v_id int UNSIGNED DEFAULT 0;


  IF IFNULL(pi_phone, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'phone cannot be empty';
  END IF;

  IF IFNULL(pi_otp, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'otp cannot be empty';
  END IF;
  SELECT
    u_phoneOtp,
    u_id INTO v_otp, v_id
  FROM t_users
  WHERE u_phone = LOWER(pi_phone);


  IF v_id IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'not found';
  END IF;
  IF v_otp IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'login first';
  END IF;

  IF v_otp <> pi_otp THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Баталгаажуулах код буруу байна';
  END IF;

  UPDATE t_users
  SET u_phoneOtp = NULL
  WHERE u_id = v_id;
END
$$

--
-- Create procedure `sp_user_login`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_user_login (pi_phone nvarchar(100),
pi_otp nvarchar(100))
BEGIN

  DECLARE v_id nvarchar(100);


  IF IFNULL(pi_phone, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'pi_phone cannot be empty';
  END IF;

  IF IFNULL(pi_otp, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'pi_otp cannot be empty';
  END IF;

  SELECT
    u_id INTO v_id
  FROM t_users
  WHERE u_phone = LOWER(pi_phone);

  IF v_id IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Бүртгэлгүй байна';
  END IF;
  UPDATE t_users
  SET u_phoneOtp = pi_otp,
      u_isAccountVerified = TRUE
  WHERE u_id = v_id;

END
$$

--
-- Create procedure `sp_login_user`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_login_user (pi_phone nvarchar(100),
pi_otp nvarchar(100))
BEGIN

  DECLARE v_id nvarchar(100);


  IF IFNULL(pi_phone, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'pi_phone cannot be empty';
  END IF;

  IF IFNULL(pi_otp, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'pi_otp cannot be empty';
  END IF;

  SELECT
    u_id INTO v_id
  FROM t_users
  WHERE u_phone = LOWER(pi_phone);

  IF v_id IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Бүртгэлгүй байна';
  END IF;
  UPDATE t_users
  SET u_phoneOtp = pi_otp,
      u_isAccountVerified = TRUE
  WHERE u_id = v_id;

END
$$

--
-- Create procedure `sp_create_user_account`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_user_account (pi_phone nvarchar(100),
pi_otp nvarchar(100))
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;


  IF IFNULL(pi_phone, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'pi_phone cannot be empty';
  END IF;

  IF IFNULL(pi_otp, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'pi_otp cannot be empty';
  END IF;

  SELECT
    count(1) INTO count
  FROM t_users
  WHERE u_phone = LOWER(pi_phone);

  IF count >= 1 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'alreadt exists';
  END IF;

  INSERT INTO t_users (u_phone, u_phoneOtp)
    VALUES (pi_phone, pi_otp);
END
$$

DELIMITER ;

--
-- Create table `t_feedback_user`
--
CREATE TABLE t_feedback_user (
  f_user_ip varchar(100) NOT NULL,
  PRIMARY KEY (f_user_ip)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `f_user_ip_UNIQUE` on table `t_feedback_user`
--
ALTER TABLE t_feedback_user
ADD UNIQUE INDEX f_user_ip_UNIQUE (f_user_ip);

DELIMITER $$

--
-- Create procedure `sp_submit_feedback`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_submit_feedback (pi_f_id int,
pi_ip_addr varchar(100))
sp:
  BEGIN
    DECLARE v_count int;
    DECLARE v_id int;
    DECLARE v_u_id int;
    DECLARE v_ip_count int;
    IF IFNULL(pi_f_id, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'feedback id cannot be empty';
    END IF;

    #
    SELECT
      f_id INTO v_id
    FROM t_feedback
    WHERE f_id = pi_f_id
    ;
    IF v_id IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'feedback олдсонгүй!';
    END IF;

    #
    SELECT
      f_count INTO v_count
    FROM t_feedback
    WHERE f_id = pi_f_id
    ;
    SELECT
      COUNT(*) INTO v_ip_count
    FROM t_feedback_user
    WHERE f_user_ip LIKE CONCAT('%', pi_ip_addr, '%');
    IF v_ip_count < 1 THEN
      UPDATE t_feedback
      SET f_count = v_count + 1
      WHERE f_id = pi_f_id;
      INSERT INTO t_feedback_user (f_user_ip)
        VALUES (pi_ip_addr);
    END IF;
  END
  $$

DELIMITER ;

--
-- Create table `t_crime_type`
--
CREATE TABLE t_crime_type (
  c_type_id int NOT NULL AUTO_INCREMENT,
  type_name varchar(100) DEFAULT NULL,
  PRIMARY KEY (c_type_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `type_name` on table `t_crime_type`
--
ALTER TABLE t_crime_type
ADD UNIQUE INDEX type_name (type_name);

DELIMITER $$

--
-- Create procedure `sp_show_crime`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_show_crime (pi_skip int,
pi_limit int,
pi_sort int)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE start int;
  SET start = pi_skip - 1;

  SELECT
    *
  FROM t_crime
    LEFT JOIN t_crime_type
      ON t_crime.c_type = t_crime_type.type_name
    LEFT JOIN t_crime_sub_type
      ON t_crime.c_sub_type_name = t_crime_sub_type.c_sub_type_name LIMIT start, pi_limit;
END
$$

--
-- Create procedure `sp_filter_crime_type`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_filter_crime_type (pi_type varchar(100),
pi_skip int,
pi_limit int,
pi_sort int)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE start int;
  SET start = pi_skip - 1;

  IF IFNULL(pi_type, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'type cannot be empty';
  END IF;
  SELECT
    *
  FROM t_crime
    LEFT JOIN t_crime_type
      ON t_crime.c_type = t_crime_type.type_name
  WHERE t_crime.c_type = pi_type LIMIT start, pi_limit;
END
$$

--
-- Create procedure `sp_filter_crime_subtype`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_filter_crime_subtype (pi_sub_type varchar(200),
pi_skip int,
pi_limit int,
pi_sort int)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;
  DECLARE start int;
  SET start = pi_skip - 1;
  IF IFNULL(pi_sub_type, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'sub type cannot be empty';
  END IF;
  SELECT
    *
  FROM t_crime
    LEFT JOIN t_crime_type
      ON t_crime.c_type = t_crime_type.type_name
    LEFT JOIN t_crime_sub_type
      ON t_crime.c_sub_type_name = t_crime_sub_type.c_sub_type_name
  WHERE t_crime.c_sub_type_name = pi_sub_type LIMIT start, pi_limit;
END
$$

DELIMITER ;

--
-- Create table `t_management_team`
--
CREATE TABLE t_management_team (
  man_id int NOT NULL AUTO_INCREMENT,
  man_firstName varchar(100) DEFAULT NULL,
  man_lastName varchar(100) DEFAULT NULL,
  man_position text DEFAULT NULL,
  man_img text DEFAULT NULL,
  createdAt timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (man_id),
  UNIQUE INDEX man_id (man_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 15,
AVG_ROW_LENGTH = 1170,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

DELIMITER $$

--
-- Create procedure `sp_create_man_team`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_man_team (pi_img text,
pi_firstName mediumtext,
pi_lastName mediumtext,
pi_position longtext)
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;

  IF IFNULL(pi_img, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'image cannot be empty';
  END IF;

  IF IFNULL(pi_position, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'position cannot be empty';
  END IF;

  IF IFNULL(pi_firstName, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'first name cannot be empty';
  END IF;

  IF IFNULL(pi_lastName, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'last name cannot be empty';
  END IF;

  INSERT INTO t_management_team (man_firstName, man_lastName, man_position, man_img)
    VALUES (pi_firstName, pi_lastName, pi_position, pi_img);
  SELECT
    MAX(man_id) AS man_id
  FROM t_management_team;

END
$$

DELIMITER ;

--
-- Create table `t_admins`
--
CREATE TABLE t_admins (
  a_id int NOT NULL AUTO_INCREMENT,
  a_username varchar(100) NOT NULL,
  a_password varchar(100) NOT NULL,
  PRIMARY KEY (a_id),
  UNIQUE INDEX a_id (a_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `a_name` on table `t_admins`
--
ALTER TABLE t_admins
ADD UNIQUE INDEX a_name (a_username);

DELIMITER $$

--
-- Create procedure `sp_login_admin`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_login_admin (pi_username varchar(100),
pi_passhash varchar(100))
sp:
  BEGIN

    DECLARE v_username varchar(100);
    DECLARE v_passhash varchar(100);
    DECLARE v_id int;
    #

    IF IFNULL(pi_username, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'username cannot be empty';
    END IF;

    IF IFNULL(pi_passhash, '') = '' THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'password cannot be empty';
    END IF;

    #
    SELECT
      a_id,
      a_username,
      a_password INTO v_id, v_username, v_passhash
    FROM t_admins
    WHERE a_username = pi_username
    LIMIT 1
    ;


    IF v_username IS NULL THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'not found';
    END IF;

    IF v_passhash <> SHA2(pi_passhash, 256) THEN
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'wrong password';
    END IF;
    SELECT
      a_id
    FROM t_admins
    WHERE a_id = v_id;
  END
  $$

--
-- Create procedure `sp_create_admin_account`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE sp_create_admin_account (pi_username nvarchar(100),
pi_passhash nvarchar(100))
BEGIN

  DECLARE count int UNSIGNED DEFAULT 0;


  IF IFNULL(pi_username, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'username cannot be empty';
  END IF;

  IF IFNULL(pi_passhash, '') = '' THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'password cannot be empty';
  END IF;

  SELECT
    count(1) INTO count
  FROM t_admins
  WHERE a_username = LOWER(pi_username);

  IF count >= 1 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'already exists';
  END IF;

  INSERT INTO t_admins (a_username, a_password)
    VALUES (LOWER(pi_username), SHA2(pi_passhash, 256));
  SELECT
    MAX(a_id) AS a_id
  FROM t_admins;
END
$$

DELIMITER ;

--
-- Create table `t_faq_key`
--
CREATE TABLE t_faq_key (
  key_id int NOT NULL AUTO_INCREMENT,
  key_name varchar(100) DEFAULT NULL,
  PRIMARY KEY (key_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `key_name` on table `t_faq_key`
--
ALTER TABLE t_faq_key
ADD UNIQUE INDEX key_name (key_name);

--
-- Create table `t_faq`
--
CREATE TABLE t_faq (
  f_id int NOT NULL AUTO_INCREMENT,
  f_question text DEFAULT NULL,
  f_answer text DEFAULT NULL,
  PRIMARY KEY (f_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `t_employee`
--
CREATE TABLE t_employee (
  emp_id int NOT NULL AUTO_INCREMENT,
  emp_f_name varchar(100) DEFAULT NULL,
  emp_l_name varchar(100) DEFAULT NULL,
  emp_position varchar(100) DEFAULT NULL,
  emp_phone int DEFAULT NULL,
  emp_work_phone int DEFAULT NULL,
  PRIMARY KEY (emp_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 104,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;


-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;